# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: open-cluster-management-policies

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
- |-
  apiVersion: policy.open-cluster-management.io/v1
  kind: Policy
  metadata:
    name: policy-consolelink
    namespace: open-cluster-management-policies
  spec:
    policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-securitycontextconstraints-example
        spec:
          object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: console.openshift.io/v1
              kind: ConsoleLink
              metadata:
                name: acm-console-link
              spec:
                applicationMenu:
                  imageURL: https://www.vectorlogo.zone/logos/openshift/openshift-icon.svg
                href: TO_BE_OVERRIDDEN_WITH_RHACM_WEB_CONSOLE_URL
- |-
  apiVersion: policy.open-cluster-management.io/v1
  kind: Policy
  metadata:
    name: policy-auth-provider
    namespace: open-cluster-management-policies
  spec:
    policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-auth-provider
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            data:
              htpasswd: "OVERRIDDEN_BASE64_ENCODED_HTPASSWD_FILE_CONTENTS"
            kind: Secret
            metadata:
              name: htpass-secret
              namespace: openshift-config
# list of Resource Config to be Applied
resources:
  - policy-auth-provider.yaml
  - policy-console-link.yml
  # - policy-scc.yaml
  - dev-clusters-placementrule.yaml
  - production-clusters-placementrule.yaml
  - policy-namespace.yaml
  - policy-rolebinding.yaml
  - policy-imagemanifestvuln.yaml
  - policy-certificate.yaml
  - policy-role.yaml
  - policy-iam.yaml