---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-auth-provider
  namespace: open-cluster-management-policies
spec:
  object-templates:
    - complianceType: musthave
      objectDefinition:
        data:
          htpasswd: ""
        kind: Secret
        metadata:
          name: htpass-secret
          namespace: openshift-config
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-consolelink
  namespace: open-cluster-management-policies
spec:
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-securitycontextconstraints-example
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: console.openshift.io/v1
            kind: ConsoleLink
            metadata:
              name: acm-console-link
            spec:
              applicationMenu:
                imageURL: https://www.vectorlogo.zone/logos/openshift/openshift-icon.svg
              href: https://multicloud-console.apps.kilo.demo.red-chesterfield.com/multicloud/clusters
---
